use_frameworks!

target 'PodTestLib_Example' do
  pod 'PodTestLib', :path => '../'

  target 'PodTestLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
